export interface MedicalTerm {
    category: string;
    term: string;
    definition: string;
    laymanTerm: string;
    normalRange: string;
    details: string;
}

export const MedicalTerms: MedicalTerm[] = [
    {
        category: "Diagnosis",
        term: "Hematocrit",
        definition: "Measurement of the percentage of red blood cells in the whole blood.",
        laymanTerm: "The amount of red blood cells in the blood.",
        normalRange: "Newborns: 55-68%; Children: 36-40%; Adult Males: 42-54%; Adult Women: 38-46%",
        details: "Normal ranges are dependent on the age and gender of individuals.",
    },
    {
        category: "Symptoms",
        term: "Inflammation",
        definition: "A localised reaction that produces redness, warmth, swelling, and pain as a result of infection, irritation, or injury. Inflammation can be external or internal.",
        laymanTerm: "A reaction that will cause your body to feel redness, swelling, warmth and pain",
        normalRange: "NA",
        details: "NA",
    },
    {
        category: "Diagnosis",
        term: "ECG (Electrocardiogram)",
        definition: "The measurement is used to determine the electrical activity of the heart. It can be used to check the heart conditions of the patients.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "NA",
    },
    {
        category: "Disease",
        term: "Hyperlipidemia",
        definition: "Higher lipid levels in the blood than normal.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "This can be inherited and become the risk factor for heart diseases.",
    },
    {
        category: "Disease",
        term: "Hypertension",
        definition: "High blood pressure.",
        laymanTerm: "NA",
        normalRange: "Systolic blood pressure higher than 140mmHg, diastolic blood pressure lower than 90mmHg",
        details: "Chronic hypertension may be asymptomatic but will lead to other diseases such as kidney failure.",
    },
    {
        category: "Disease",
        term: "Hypoglycemia",
        definition: "Low blood glucose level.",
        laymanTerm: "Low blood sugar level.",
        normalRange: "3.9mmol/L to 5.6mmol/L",
        details: "Symptoms: Anxiety, nausea, if brain lack of glucose will cause symptoms such as headache, mild confusion, loss of consciousness.",
    },
    {
        category: "Drug",
        term: "Ibuprofen",
        definition: "The classification of this drug is nonsteroidal anti-inflammatory(NSAID) drug.",
        laymanTerm: "NA",
        normalRange: "Dosage: Initially take 400mg (2 tablets). One to two tablets may be taken when required",
        details: "Ibuprofen is used for mild pain, fever and swelling.",
    },
    {
        category: "Disease",
        term: "Cerebral edema",
        definition: "Accumulation of excessive fluids in the brain.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "Symptoms: Headache, nausea, vomiting, seizure, coma.",
    },
    {
        category: "Disease",
        term: "Arthritis",
        definition: "Inflammation occurs on the joint.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "Symptoms: Pain, swelling, redness, stiffness.",
    },
    {
        category: "Disease",
        term: "Dermatitis",
        definition: "Inflammation occurs on skin.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "Cause: Inherent skin defect, interact with allergens.\nSymptoms: Redness, itchy, blistering\nTreatment: Steroid cream.",
    },
    {
        category: "Drug",
        term: "Warfarin",
        definition: "This is an anticoagulant drug. It can be used to reduce the risks of stroke and heart attack.",
        laymanTerm: "NA",
        normalRange: "Dosage: This is a narrow therapeutic index drug so it depends on individual conditions and should be monitored by healthcare professionals.",
        details: "Warfarin undergoes drug-drug interactions with a variety of drugs (e.g. acetaminophen, aspirin, antibiotics) and vitamins. Patients should inform prescribers their medication history before taking warfarin.",
    },
    {
        category: "Disease",
        term: "Laryngitis",
        definition: "Inflammation occurs on the larynx (a part of the throat).",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "Symptoms: Sore throat, fever, sometimes will also affect the vocal cords.",
    },
    {
        category: "Disease",
        term: "Leukaemia",
        definition: "Cancer of the blood cells.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "Treatment: Chemotherapy, radiation therapy, bone marrow transplantation.",
    },
    {
        category: "Metabolism",
        term: "Creatinine",
        definition: "This is a muscle metabolic waste. The creatinine level in the body can be used as an indicator to determine the kidney function.",
        laymanTerm: "NA",
        normalRange: "Male: 0.6-1.2 mg/dL\nFemale: 0.5-1.1 mg/dL",
        details: "Some drugs such as cimetidine, corticosteroids, and salicylates can cause elevation of creatinine.",
    },
    {
        category: "Disease",
        term: "Obesity",
        definition: "The person who accumulates extra body fat.",
        laymanTerm: "NA",
        normalRange: "BMI is the screening tool to diagnose obesity.\nUnderweight: <18.5\nNormal: 18.5-24.9\nOverweight: 25-29.9\nObesity: >30",
        details: "NA",
    },
    {
        category: "Disease",
        term: "Parasitosis",
        definition: "Parasite infection.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "NA",
    },
    {
        category: "Disease",
        term: "Seizure",
        definition: "A sudden and uncontrolled electrical disturbance in the brain which will affect the awareness, movement and behaviour of the person.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "NA",
    },
    {
        category: "Disease",
        term: "Fracture",
        definition: "The disruption or break in the continuity of bone or cartilage.",
        laymanTerm: "NA",
        normalRange: "NA",
        details: "Mostly caused by trauma. The severity depends on the location of break and the type of fracture.",
    },
    {
        category: "Drugs",
        term: "Tamoxifen",
        definition: "This is an antiestrogen drug which is used to treat breast cancer.",
        laymanTerm: "A drug to treat breast cancer.",
        normalRange: "NA",
        details: "Tamoxifen treats breast cancer by competing the estrogen receptors with the estrogen.",
    },
    {
        category: "Diagnose",
        term: "Leukocyte Count / White blood cell count (WBC)",
        definition: "The total number of white blood cells in the blood. This is a composition of the measurement of complete blood count (CBC).",
        laymanTerm: "The number of white blood cells in the blood.",
        normalRange: "4.5 to 11.0 * 10^9/L",
        details: "Low WBC is called leukopenia, while high WBC is called leukocytosis.",
    },
];